export interface ClienteData {
    $id: string;
    $values: Cliente[];
  }
  
  export interface Cliente {
    $id: string;
    lngClienteId: string;
    strDvClienteId: string;
    strNombre: string;
    strSoundexNombre: string;
    intEstadoCliente: number;
    intEstadoSuministro: number;
    intEstadoFacturacion: number;
    strDireccion: string;
    strSoundexDir: string;
    intDepto: number;
    intZona: number;
    intMunicipio: number;
    intBarrio: number;
    intCentroPoblado: number;
    intCodigoArea: number;
    strInformacionAdicional: string | null;
    lngTelefono: number;
    lngTelefonoCelular: number;
    lngTelefonoContacto: number;
    strTieneDirPostal: string | null;
    strFichaCatastral: string;
    lngNit: number;
    strApellido1: string;
    strApellido2: string | null;
    strNombre1: string;
    strNombre2: string | null;
    intTipoPersona: number;
    strCodigoEntidad: string | null;
    intCiclo: number;
    lngRutaLectura: number;
    intTarifa: number;
    intGrupoCu: number;
    intClaseServicio: number;
    intEstrato: number;
    intMedidaTension: number;
    intNroMedidores: number;
    decFactorUtilizacion: number;
    dblCargaContratada: number;
    dblCargaInstalada: number;
    dblCargaAdicional: number;
    decFactorAdicional: number;
    decFactorReferencia: number;
    strCargaAforada: string;
    intNumeroDias: number;
    strExentoIntereses: string;
    strExentoSuspension: string;
    strIndSaldo: string;
    strIndCritica: string;
    strIndFacturacion: string;
    intCantidadCasas: number;
    intTipoVencimiento: number;
    intTipoBloqueo: number;
    strTipoCliente: string | null;
    intConsecutivo: number;
    intCorrCreditos: number;
    intCorrPagos: number;
    intFechaCreacion: number;
    intFechaAccion: number;
    intFechaLecturaAnt: number;
    intFechaLecturaAct: number;
    intFechaFacturacionAnt: number;
    intFechaFacturacionAct: number;
    intAntiguedadSaldo: number;
    lngSaldoActual: number;
    dblInteresesMes: number;
    dblInteresesAcumulados: number;
    strCodigoSie: string;
    intCodigoCiu: number;
    strCodigoSic: string | null;
    strModoRecaudo: string | null;
    strInstaladorId: string | null;
    intMotivoRechazo: number;
    intNroFormulario: number | null;
    intPuntoSuspension: number;
    strCorreo: string | null;
    dblFactorImpuesto: number;
    strResponsable: string | null;
    strMatriculaInmobiliaria: string;
    dblGpsLatitud: number;
    dblGpsLongitud: number;
    lngClienteIdRef: number | null;
    strCalificacion: string;
    strDocumentoTipo: string;
    intCodigoGrupo: number | null;
    strTipoRecibo: string;
    strAutorizaDatos: string | null;
    strSegmentoMercado: string;
    strTipoServicio: string;
    strNumeroDocumento: string;
    strCondicionPredio: string | null;
    strTipoFacturacion: string;
    personaId: number | null;
    strDEstadoCliente: string;
    strDEstadoFacturacion: string;
    strDCiclo: string;
    lngTipoCiclo: number;
    strTipoCicloChar: string;
    strRlZona: string;
    strRlMunicipio: string;
    strRlSeccion: string;
    strRlOrden: string;
    strDireccionInf: string;
    strDZona: string;
    strDMunicipio: string;
    strDBarrio: string;
    strDEstrato: string;
    dblEstratoMedida: number;
    strDEstadoSuministro: string;
    strDClaseServicio: string;
    strTipoConsumo: string | null;
    strDTarifa: string;
    strTarifaProvisional: string;
    dblSaldoTotal: number;
    strDTipoBloqueo: string;
    strRollBloqueo: string | null;
    strDGrupoCu: string;
    strObservaciones: string | null;
    strDPuntoSuspension: string;
    strDTipoPersona: string;
    dTipoServicio: string;
    strCsEstratoMedida: string;
    strEstadoActual: string;
    rutaReparto: number;
    puntajeSisben: number | null;
    estratoCriterio: number | null;
    tipoInfoPredial: number;
    gpsAltitud: number;
    condicionEspecial: number;
    mensajeriaInstantanea: string | null;
    dDepto: string;
  }
  
